<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="AWSSDK.Core" Version="4.0.3.3" />
	<PackageReference Include="MassTransit" Version="8.5.1" />
	<PackageReference Include="MassTransit.AmazonSQS" Version="8.5.1" />
	<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\fiap-esperanca-solidaria-usuario-domain\FiapEsperancaSolidaria.Usuario.Domain.csproj" />
    <ProjectReference Include="..\fiap-esperanca-solidaria-usuario-observability\FiapEsperancaSolidaria.Usuario.Observability.csproj" />
    <ProjectReference Include="..\fiap-esperanca-solidaria-usuario-shared\FiapEsperancaSolidaria.Usuario.Shared.csproj" />
  </ItemGroup>
</Project>