name: CD - Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  publish-image:
    name: Build, Test and Publish Docker Image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: 01 - Checkout application
        uses: actions/checkout@v4

      - name: 02 - Validate tag belongs to develop branch
        run: |
          git fetch origin develop

          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/develop; then
            echo "::error::The tag '$GITHUB_REF_NAME' is not on the develop branch."
            exit 1
          fi

      - name: 03 - Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: 04 - Restore
        run: dotnet restore fiap-esperanca-solidaria-usuario-api.slnx

      - name: 05 - Build
        run: dotnet build fiap-esperanca-solidaria-usuario-api.slnx --configuration Release --no-restore

      - name: 06 - Run Tests
        run: dotnet test fiap-esperanca-solidaria-usuario-api.slnx --configuration Release --no-build

      - name: 07 - Build Docker Image
        working-directory: ${{ github.workspace }}
        run: |
          docker build \
            -f dockerfile/Dockerfile \
            -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG \
            -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest \
            .

      - name: 08 - Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 09 - Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: image
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'

      - name: 10 - Push Docker Images
        run: |
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest