name: CI - Pull Request Validation

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened # Quando o PR é criado
      - synchronize # Quando novos commits são enviados para um PR já existente
      - reopened # Quando um PR é fechado e depois reaberto
      - ready_for_review # Quando um PR é criado como rascunho e depois marcado como pronto para revisão

  workflow_dispatch:

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: 01 - Checkout code
        uses: actions/checkout@v4

      - name: 02 - Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: 03 - Restore dependencies
        run: dotnet restore fiap-esperanca-solidaria-usuario-api.slnx

      - name: 04 - Build solution
        run: dotnet build fiap-esperanca-solidaria-usuario-api.slnx --configuration Release --no-restore

      - name: 05 - Run tests with coverage
        run: >
          dotnet test
          fiap-esperanca-solidaria-usuario-api.slnx 
          --configuration Release
          --no-build
          --collect:"XPlat Code Coverage"

      - name: 06 - Check vulnerable packages
        shell: bash
        run: |
          dotnet package list \
            --project fiap-esperanca-solidaria-usuario-api.slnx \
            --include-transitive \
            --vulnerable \
            --format json \
            > vulnerable.json

          cat vulnerable.json

          if grep -q '"vulnerabilities"' vulnerable.json; then
            echo "::error::Vulnerable NuGet packages were found."
            exit 1
          fi

          echo "No vulnerable NuGet packages found."

      - name: 07 - Check outdated packages
        shell: bash
        run: |
          dotnet package list --project fiap-esperanca-solidaria-usuario-api.slnx --outdated > outdated.txt

          cat outdated.txt

          if grep -Eqi "outdated package|outdated packages" outdated.txt; then
            echo "::warning::Outdated NuGet packages were found."
          fi